export const categoryData = [
  {
    id: 1,
    name: "Museums",
    value: "museum",
    icon: "/category-images/museum.png",
  },
  {
    id: 2,
    name: "Monuments",
    value: "monument",
    icon: "/category-images/monument.png",
  },
  {
    id: 3,
    name: "Parks",
    value: "park",
    icon: "/category-images/park.png",
  },
  {
    id: 4,
    name: "Cathedrals",
    value: "cathedral",
    icon: "/category-images/cathedral.png",
  },
  {
    id: 5,
    name: "Art Galleries",
    value: "art_gallery",
    icon: "/category-images/art_gallery.png",
  },
  {
    id: 6,
    name: "Zoos",
    value: "zoo",
    icon: "/category-images/zoo.png",
  },
  {
    id: 7,
    name: "Beaches",
    value: "beach",
    icon: "/category-images/beach.png",
  },
  {
    id: 8,
    name: "Historical Sites",
    value: "historical_site",
    icon: "/category-images/historical_site.png",
  },
  {
    id: 9,
    name: "Libraries",
    value: "library",
    icon: "/category-images/library.png",
  },
  {
    id: 10,
    name: "Aquariums",
    value: "aquarium",
    icon: "/category-images/aquarium.png",
  },
  {
    id: 11,
    name: "Botanical Gardens",
    value: "botanical_garden",
    icon: "/category-images/botanical_garden.png",
  },
  {
    id: 12,
    name: "Castles",
    value: "castle",
    icon: "/category-images/castle.png",
  },
  {
    id: 13,
    name: "Observatories",
    value: "observatory",
    icon: "/category-images/observatory.png",
  },
  {
    id: 14,
    name: "Markets",
    value: "market",
    icon: "/category-images/market.png",
  },
  {
    id: 15,
    name: "Stadiums",
    value: "stadium",
    icon: "/category-images/stadium.png",
  },
  {
    id: 16,
    name: "Theaters",
    value: "theater",
    icon: "/category-images/theater.png",
  },
  {
    id: 17,
    name: "Waterfalls",
    value: "waterfall",
    icon: "/category-images/waterfall.png",
  },
  {
    id: 18,
    name: "Wineries",
    value: "winery",
    icon: "/category-images/winery.png",
  },
  {
    id: 19,
    name: "Farms",
    value: "farm",
    icon: "/category-images/farm.png",
  },
];
