name: Generate .env File

on:
  push:
    branches:
      - main

jobs:
  generate-env:
    runs-on: ubuntu-latest
    env:
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
      NEXT_PUBLIC_GOOGLE_API_KEY: ${{ secrets.NEXT_PUBLIC_GOOGLE_API_KEY }}

    steps:
      - name: Create .env file
        run: |
          echo "GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}" >> .env
          echo "GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}" >> .env
          echo "GOOGLE_API_KEY=${GOOGLE_API_KEY}" >> .env
          echo "NEXT_PUBLIC_GOOGLE_API_KEY=${NEXT_PUBLIC_GOOGLE_API_KEY}" >> .env

      - name: Display .env contents
        run: cat .env