name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Create .env file
        run: |
          echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> .env
          echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> .env
          echo "GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}" >> .env
          echo "NEXT_PUBLIC_GOOGLE_API_KEY=${{ secrets.NEXT_PUBLIC_GOOGLE_API_KEY }}" >> .env

      - name: Verify .env file contents
        run: |
          echo ".env file content:"
          cat .env

      - name: Check if .env file exists
        run: |
          if [ -f .env ]; then
            echo ".env file created successfully."
          else
            echo "Error: .env file not created."
            exit 1
          fi

      # Add deployment step here based on your deployment method
      # - name: Deploy to Vercel
      #   run: npx vercel --token ${{ secrets.VERCEL_TOKEN }}
