name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          # Add commands here to install necessary tools or dependencies
          # For example, for a static site, this might just be copying files
          echo "Installing dependencies..."

      - name: Build and deploy
        run: |
          # Command for building or compiling your project
          # For example:
          # npm run build or another command relevant to your project
          echo "Building project..."

      - name: Create .env file
        run: |
          echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> .env
          echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> .env
          echo "GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}" >> .env
          echo "NEXT_PUBLIC_GOOGLE_API_KEY=${{ secrets.NEXT_PUBLIC_GOOGLE_API_KEY }}" >> .env

      - name: Deploy to server or publish artifacts
        run: |
          # Commands for deploying your project, e.g., uploading to a server or publishing artifacts
          echo "Deploying project..."